name: main
on:
  pull_request:
  push:
  schedule:
    # Prime the caches every Monday
    - cron: 0 1 * * MON
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        ocaml-compiler:
          - "5.2"
          - "4.14"
        os:
          - ubuntu-latest       # Linux x86_64
          - macos-latest        # MacOS x86_64
          - macos-14            # MacOS ARM64
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout-code
        uses: actions/checkout@v4
      - name: setup-ocaml-${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v3
        with:
          opam-pin: false
          opam-depext: false
          ocaml-compiler: ${{ matrix.ocaml-compiler }}
      - run: opam install . --deps-only --with-test
      - run: opam exec -- dune build
      - run: opam exec -- dune runtest
